channels:
  - conda-forge
  - uibcdf
dependencies:
  - python=3.10
  - openff-toolkit=0.16.10
  - openff-interchange=0.4.2
  - openff-units=0.3.1
  - openff-utilities=0.1.15
  - openff-recharge=0.5.3
  - ambertools=23.6
  - lomap2=3.2.1
  - rdkit=2024.03.1
