name: bump

on: workflow_dispatch
  # pull_request:
  #   types: [closed]



permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    if: |
        github.event.pull_request.merged == true ||
        contains(github.event.pull_request.labels.*.name, 'major') ||
        contains(github.event.pull_request.labels.*.name, 'minor') ||
        contains(github.event.pull_request.labels.*.name, 'patch')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          fetch-depth: 0

      - uses: astral-sh/setup-uv@v5

      - name: Determine bump type
        id: bumptype
        run: |
          BUMP="patch"
          if [[ "${{ contains(github.event.pull_request.labels.*.name, 'major') }}" == "true" ]]; then
            BUMP="major"
          elif [[ "${{ contains(github.event.pull_request.labels.*.name, 'minor') }}" == "true" ]]; then
            BUMP="minor"
          fi
          echo "bump_type=$BUMP" >> $GITHUB_OUTPUT

      - name: Bump version
        if: steps.bumptype.outputs.bump_type != ''
        id: bumpversion
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b automation/bump-version-${{ github.run_id }}

          uv version --bump ${{ steps.bumptype.outputs.bump_type }}
          NEW_VERSION=$(uv version | cut -d' ' -f2)
          echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

          git add pyproject.toml uv.lock
          git commit -m "Bump to v$NEW_VERSION [skip ci]"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v8
        with:
          token: ${{ secrets.AUTOMATION_PAT }}
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          branch: automation/bump${{ steps.bumpversion.outputs.version }}
          title: "Bump version to v${{ steps.bumpversion.outputs.version }}"
          body: "Automated version bump (v${{ steps.bumpversion.outputs.version }}) triggered by PR #${{ github.event.pull_request.number }}"
          base: main
          auto-merge: true
          merge-method: squash

  tag:
    needs: bump
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.AUTOMATION_PAT }}

      - uses: astral-sh/setup-uv@v5

      - name: Create and push tags
        run: |
          TAG="${{ needs.bump.bumpversion.outputs.version }}"
          git tag "$TAG"
          git push origin "$TAG"

          git tag -f latest
          git push -f origin latest
