name: check

on:
  workflow_dispatch:
  pull_request:
    types: [opened, ready_for_review]
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'create-pull-request/patch') }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          BUMP="patch"