name: check

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened,ready_for_review]
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    if: github.ref_name != 'create-pull-request/patch'
    steps:
      - uses: actions/checkout@v4
      - run: |
          BUMP="patch"