name: Push tags

on:
  push:
    branches:
      - main

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Check if tag already exists
        id: check_tag
        run: |
          VERSION=$(uv version | cut -d' ' -f2)

          TAG="v$VERSION"
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create and push tags
        if: steps.check_tag.outputs.exists == 'false'
        run: |
          TAG="${{ steps.version.check_tag.tag }}"
          git tag "$TAG"
          git push origin "$TAG"

          git tag -f latest
          git push -f origin latest
