name: Push tags

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  create-tag:
    if: |
      github.event.pull_request.merged == true && (
        contains(github.event.pull_request.labels.*.name, 'major') ||
        contains(github.event.pull_request.labels.*.name, 'minor') ||
        contains(github.event.pull_request.labels.*.name, 'patch')
      )
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Setup uv
        uses: astral-sh/setup-uv@v5

      - name: Create and Push Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          CURRENT_VERSION=$(uv version | cut -d' ' -f2)
          git tag -a "v$CURRENT_VERSION" -m "New v$CURRENT_VERSION"
          git tag -a "latest"

          git push origin main -f --tags
